// Generated by https://quicktype.io

export interface Contact {
  id:         number;
  name:       string;
  telNum:     string;
  address:    string;
  email:      string;
  birthday:   string;
  collection: number;
}
